### ISSUE TITLE
indeed-job-scraper update available

### ISSUE THREAD

**Issue by ShenoudaGergis** [marro73/Uni-job#1]
Hi
You can now use the updated version of <a href="https://www.npmjs.com/package/indeed-job-scraper">`indeed-job-scraper`</a> package.
Bug reports are always welcome :)

**Comment by elliot736** [comment]
Hi, I'm very sorry for the late reply.
Thank you very much for the update, it's such a brilliant code, but sadly indeed was blocking my requests after like 10 minutes, even when I put a limit for requests to be only 10 or 5.

**Comment by ShenoudaGergis** [comment]
No worries, you don't have to be sorry :).
I have implemented that piece of code to help others searching for a job just for fun you know, and i saw that you use it so i came to tell you for the update. the old version stopped working I guess because indeed from time to time change their pages structure that's why an empty result is returned, this type of code has to be actively maintained for this sort of reasons.

Good Luck.

**Comment by elliot736** [comment]
Thank you for your answer and for the good work, I will definitely give
it a try and report to you back in case of any bugs.
